#!/bin/bash

if [ -z "$SPARK_USER_NAME" ] || [ -z "$SPARK_USER_ID" ] || [ -z "$SPARK_GROUP_NAME" ] || [ -z "$SPARK_GROUP_ID" ]
then
  echo "Please set all required environment variables."
  exit 1
fi

setup-users

APPLICATION_DIR=/submit.$$

mkdir $APPLICATION_DIR

chown -R $SPARK_USER_NAME $APPLICATION_DIR
chgrp -R $SPARK_GROUP_NAME $APPLICATION_DIR
chown -R $SPARK_USER_NAME $SPARK_HOME
chgrp -R $SPARK_GROUP_NAME $SPARK_HOME

cd $APPLICATION_DIR

exec sudo -E -u $SPARK_USER_NAME $SPARK_HOME/bin/spark-submit "$@"
