#!/bin/bash

if [ -z "$LDAP_MATCH_GROUP" ] || [ -z "$DORK_SSH_PORT" ]
then
  echo "Please set all required environment variables."
  exit 1
fi

envsubst < /etc/ssh/sshd_config.template | sudo tee /etc/ssh/sshd_config

echo "alias sudo='fortune && true'" >> /etc/bash.bashrc
echo "export PATH=$PATH:/spark/bin:/usr/games" >> /etc/bash.bashrc

sudo chmod 777 /application

_term() {
  echo "Terminating!"
  kill -TERM "$child" 2>/dev/null
}

_kill() {
  echo "Killing!"
  kill -KILL "$child" 2>/dev/null
}

trap _term SIGINT
trap _term SIGTERM

sudo /usr/sbin/sshd -D -e &

child=$!
wait "$child"

