#!/bin/bash

if [ -z "$SPARK_USER_NAME" ] || [ -z "$SPARK_USER_ID" ] || [ -z "$SPARK_GROUP_NAME" ] || [ -z "$SPARK_GROUP_ID" ]
then
  echo "Please set all required environment variables."
  exit 1
fi

setup-users

SUBMIT_DIR=/submit.$$

mkdir $SUBMIT_DIR

if [[ $SPARK_APPLICATION_SOURCE ]] || [[ $SPARK_APPLICATION_TARGET ]]; then
  if [[ -z $SPARK_APPLICATION_SOURCE ]] || [[ -z $SPARK_APPLICATION_TARGET ]]; then
    echo 'If either $SPARK_APPLICATION_SOURCE or $SPARK_APPLICATION_TARGET is set, both must be set!'
    exit 1
  else
    filename=$(basename "$SPARK_APPLICATION_SOURCE")
    destination="$SPARK_APPLICATION_TARGET/$filename"
    echo "Downloading $SPARK_APPLICATION_SOURCE to $destination"
    mkdir -p "$SPARK_APPLICATION_TARGET"
    if [[ "$SPARK_APPLICATION_USERNAME" ]] && [[ "$SPARK_APPLICATION_PASSWORD" ]]; then
      wget --user="$SPARK_APPLICATION_USERNAME" --password="$SPARK_APPLICATION_PASSWORD" -P "$SPARK_APPLICATION_TARGET" "$SPARK_APPLICATION_SOURCE"
    else
      wget -P "$SPARK_APPLICATION_TARGET" "$SPARK_APPLICATION_SOURCE"
    fi

    cd "$SPARK_APPLICATION_TARGET"
    if [[ "$filename" == *.tar.gz ]] || [[ "$filename" == *.tgz ]]; then
      tar -xvzf $filename
    elif [[ "$filename" == *.tar.bz2 ]] || [[ "$filename" == *.tbz2 ]]; then
      tar -xvjf $filename
    elif [[ "$filename" == *.tar ]]; then
      tar -xvf $filename
    fi
    cd -
  fi
fi

chown -R $SPARK_USER_NAME $SUBMIT_DIR
chgrp -R $SPARK_GROUP_NAME $SUBMIT_DIR
chown -R $SPARK_USER_NAME $SPARK_HOME
chgrp -R $SPARK_GROUP_NAME $SPARK_HOME

cd $SUBMIT_DIR

exec sudo -E -u $SPARK_USER_NAME $SPARK_HOME/bin/spark-submit "$@"
