#!/bin/bash

if [ -z "$SPARK_PORT_DRIVER" ] \
  || [ -z "$SPARK_PORT_FILESERVER" ] \
  || [ -z "$SPARK_PORT_BROADCAST" ] \
  || [ -z "$SPARK_PORT_REPL_CLASS_SERVER" ] \
  || [ -z "$SPARK_PORT_BLOCK_MANAGER" ] \
  || [ -z "$SPARK_PORT_EXECUTOR" ] \
  || [ -z "$SPARK_MASTER_IP" ] \
  || [ -z "$SPARK_MASTER_PORT" ] \
  || [ -z "$SPARK_MASTER_WEBUI_PORT" ] \
  || [ -z "$SPARK_LOCAL_IP" ] \
  || [ -z "$SPARK_USER_NAME" ] \
  || [ -z "$SPARK_USER_ID" ] \
  || [ -z "$SPARK_GROUP_NAME" ] \
  || [ -z "$SPARK_GROUP_ID" ]
then
  echo "Please set all required environment variables."
  exit 1
fi

setup-users

export SPARK_MASTER_OPTS="$SPARK_MASTER_OPTS -Dspark.driver.port=$SPARK_PORT_DRIVER \
-Dspark.fileserver.port=$SPARK_PORT_FILESERVER \
-Dspark.broadcast.port=$SPARK_PORT_BROADCAST \
-Dspark.replClassServer.port=$SPARK_PORT_REPL_CLASS_SERVER \
-Dspark.blockManager.port=$SPARK_PORT_BLOCK_MANAGER \
-Dspark.executor.port=$SPARK_PORT_EXECUTOR \
-Dspark.broadcast.factory=org.apache.spark.broadcast.HttpBroadcastFactory \
-XX:+UseG1GC \
-XX:MaxGCPauseMillis=1000"


echo "checking master recovery dir $SPARK_MASTER_RECOVERY_DIRECTORY"
if [ "$SPARK_MASTER_RECOVERY_DIRECTORY" ]
then
  if [ -d "$SPARK_MASTER_RECOVERY_DIRECTORY" ]
  then
    export SPARK_DAEMON_JAVA_OPTS="-Dspark.deploy.recoveryMode=FILESYSTEM -Dspark.deploy.recoveryDirectory=$SPARK_MASTER_RECOVERY_DIRECTORY"
    sudo chown -R "$SPARK_USER_NAME":"$SPARK_GROUP_NAME" "$SPARK_MASTER_RECOVERY_DIRECTORY"
  else
    echo "SPARK_MASTER_RECOVERY_DIRECTORY=$SPARK_MASTER_RECOVERY_DIRECTORY is not a directory"
    exit 1
  fi
fi

echo "using master opts: $SPARK_MASTER_OPTS"
echo "using deamon java opts: $SPARK_DAEMON_JAVA_OPTS"

sudo chown -R "$SPARK_USER_NAME":"$SPARK_GROUP_NAME" "$SPARK_HOME"

echo "Trying to sudo to Spark user:"

sudo -u "$SPARK_USER_NAME" id

exec sudo -E -u "$SPARK_USER_NAME" "$SPARK_HOME"/bin/spark-class org.apache.spark.deploy.master.Master \
    --ip "$SPARK_MASTER_IP" \
    --port "$SPARK_MASTER_PORT" \
    --webui-port "$SPARK_MASTER_WEBUI_PORT" \
    "$@"

